/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artifact {
  'id' : string,
  'title' : string,
  'audioUrl' : [] | [string],
  'story' : string,
}
export interface ArtifactContent {
  'id' : string,
  'title' : string,
  'audioUrl' : [] | [string],
  'story' : string,
}
export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'zone' : string,
  'notes' : string,
  'dateTime' : string,
}
export interface BookingRequestDto {
  'zone' : string,
  'notes' : string,
  'dateTime' : string,
}
export type BookingStatus = { 'Rescheduled' : null } |
  { 'RequestedAccess' : null } |
  { 'Waitlist' : null } |
  { 'CheckedIn' : null } |
  { 'NoShow' : null } |
  { 'Reservation' : null } |
  { 'Default' : null } |
  { 'Confirmed' : null } |
  { 'Denied' : null } |
  { 'Completed' : null } |
  { 'Expired' : null } |
  { 'Canceled' : null };
export interface DeliveryZone {
  'name' : string,
  'description' : string,
  'zoneId' : string,
}
export interface LoyaltyReward {
  'id' : string,
  'name' : string,
  'pointsCost' : bigint,
}
export interface LoyaltyTransaction {
  'id' : bigint,
  'description' : string,
  'timestamp' : Time,
  'isRedemption' : boolean,
  'points' : bigint,
}
export interface Membership {
  'id' : bigint,
  'name' : string,
  'photoUrl' : [] | [string],
  'identityNumber' : [] | [string],
  'isVerified' : boolean,
  'isVip' : boolean,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'customer' : Principal,
  'timestamp' : Time,
  'deliverTo' : [] | [string],
}
export type OrderStatus = { 'Delivering' : null } |
  { 'Reserved' : null } |
  { 'Paid' : null } |
  { 'Default' : null } |
  { 'Confirmed' : null } |
  { 'Ready' : null } |
  { 'Preparing' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export interface OriginMapDistrict {
  'id' : string,
  'farmerPhotoUrl' : string,
  'featuredProduct' : string,
  'name' : string,
  'description' : string,
}
export interface PackageAddOn { 'id' : string, 'name' : string }
export interface QueuePosition {
  'totalOrders' : bigint,
  'position' : bigint,
  'estimatedWaitTime' : Time,
}
export interface QueueSummary {
  'totalOrders' : bigint,
  'estimatedWaitTime' : Time,
}
export interface SocialImpactMetric {
  'id' : string,
  'value' : number,
  'name' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoyaltyReward' : ActorMethod<[LoyaltyReward], undefined>,
  'addPackage' : ActorMethod<[string, string], undefined>,
  'addPackageAddOn' : ActorMethod<[PackageAddOn], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardLoyaltyPoints' : ActorMethod<
    [bigint, string],
    {
      'newBalance' : string,
      'transactions' : [] | [Array<LoyaltyTransaction>],
      'current' : {
        'pointsBalance' : bigint,
        'transactions' : Array<LoyaltyTransaction>,
      },
      'points' : [] | [bigint],
    }
  >,
  'createArtifact' : ActorMethod<[ArtifactContent], undefined>,
  'createDeliveryZone' : ActorMethod<[DeliveryZone], undefined>,
  'createDistrict' : ActorMethod<[OriginMapDistrict], undefined>,
  'createMembership' : ActorMethod<
    [string, [] | [string], [] | [string]],
    {
      'id' : [] | [bigint],
      'name' : [] | [string],
      'photoUrl' : [] | [string],
      'identityNumber' : [] | [string],
      'existing' : [] | [Membership],
      'isVip' : [] | [boolean],
    }
  >,
  'createOrder' : ActorMethod<[[] | [string]], bigint>,
  'getAdminAnalytics' : ActorMethod<
    [],
    {
      'totalOrders' : bigint,
      'totalBookings' : bigint,
      'totalUsers' : bigint,
      'totalMembers' : bigint,
    }
  >,
  'getAdminOrdersQueue' : ActorMethod<[], Array<Order>>,
  'getAllArtifacts' : ActorMethod<[], Array<ArtifactContent>>,
  'getAllBookings' : ActorMethod<[], Array<[Principal, Array<BookingRequest>]>>,
  'getAllDistricts' : ActorMethod<[], Array<OriginMapDistrict>>,
  'getAllMemberships' : ActorMethod<[], Array<[Principal, Membership]>>,
  'getArtifactById' : ActorMethod<[string], Artifact>,
  'getAvailablePackages' : ActorMethod<[], Array<string>>,
  'getCallerBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getCallerMembership' : ActorMethod<[], [] | [Membership]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientOrders' : ActorMethod<[], Array<Order>>,
  'getCurrentLoyaltyPoints' : ActorMethod<
    [],
    [
      bigint,
      { 'pointsBalance' : bigint, 'transactions' : Array<LoyaltyTransaction> },
    ]
  >,
  'getCurrentMetrics' : ActorMethod<[], Array<SocialImpactMetric>>,
  'getDeliveryZones' : ActorMethod<[], Array<DeliveryZone>>,
  'getKitchenQueueSummary' : ActorMethod<[], QueueSummary>,
  'getLoyaltyRewards' : ActorMethod<[], Array<LoyaltyReward>>,
  'getOrderQueuePosition' : ActorMethod<[bigint], QueuePosition>,
  'getOriginMapForDistrict' : ActorMethod<[string], OriginMapDistrict>,
  'getPackageAddOns' : ActorMethod<[], Array<PackageAddOn>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemLoyaltyPoints' : ActorMethod<[string, bigint], undefined>,
  'requestBooking' : ActorMethod<[BookingRequestDto], BookingStatus>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateArtifact' : ActorMethod<[ArtifactContent], undefined>,
  'updateBookingStatus' : ActorMethod<
    [Principal, bigint, BookingStatus],
    undefined
  >,
  'updateDeliveryZone' : ActorMethod<[DeliveryZone], undefined>,
  'updateDistrict' : ActorMethod<[OriginMapDistrict], undefined>,
  'updateMetric' : ActorMethod<[SocialImpactMetric], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'verifyMembership' : ActorMethod<[Principal, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];