/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoyaltyReward = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'pointsCost' : IDL.Nat,
});
export const PackageAddOn = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LoyaltyTransaction = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : Time,
  'isRedemption' : IDL.Bool,
  'points' : IDL.Nat,
});
export const ArtifactContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'story' : IDL.Text,
});
export const DeliveryZone = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'zoneId' : IDL.Text,
});
export const OriginMapDistrict = IDL.Record({
  'id' : IDL.Text,
  'farmerPhotoUrl' : IDL.Text,
  'featuredProduct' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Membership = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'identityNumber' : IDL.Opt(IDL.Text),
  'isVerified' : IDL.Bool,
  'isVip' : IDL.Bool,
});
export const OrderStatus = IDL.Variant({
  'Delivering' : IDL.Null,
  'Reserved' : IDL.Null,
  'Paid' : IDL.Null,
  'Default' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Ready' : IDL.Null,
  'Preparing' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'timestamp' : Time,
  'deliverTo' : IDL.Opt(IDL.Text),
});
export const BookingStatus = IDL.Variant({
  'Rescheduled' : IDL.Null,
  'RequestedAccess' : IDL.Null,
  'Waitlist' : IDL.Null,
  'CheckedIn' : IDL.Null,
  'NoShow' : IDL.Null,
  'Reservation' : IDL.Null,
  'Default' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Denied' : IDL.Null,
  'Completed' : IDL.Null,
  'Expired' : IDL.Null,
  'Canceled' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'zone' : IDL.Text,
  'notes' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const Artifact = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'story' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const SocialImpactMetric = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Float64,
  'name' : IDL.Text,
});
export const QueueSummary = IDL.Record({
  'totalOrders' : IDL.Nat,
  'estimatedWaitTime' : Time,
});
export const QueuePosition = IDL.Record({
  'totalOrders' : IDL.Nat,
  'position' : IDL.Nat,
  'estimatedWaitTime' : Time,
});
export const BookingRequestDto = IDL.Record({
  'zone' : IDL.Text,
  'notes' : IDL.Text,
  'dateTime' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoyaltyReward' : IDL.Func([LoyaltyReward], [], []),
  'addPackage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPackageAddOn' : IDL.Func([PackageAddOn], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardLoyaltyPoints' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'newBalance' : IDL.Text,
          'transactions' : IDL.Opt(IDL.Vec(LoyaltyTransaction)),
          'current' : IDL.Record({
            'pointsBalance' : IDL.Nat,
            'transactions' : IDL.Vec(LoyaltyTransaction),
          }),
          'points' : IDL.Opt(IDL.Nat),
        }),
      ],
      [],
    ),
  'createArtifact' : IDL.Func([ArtifactContent], [], []),
  'createDeliveryZone' : IDL.Func([DeliveryZone], [], []),
  'createDistrict' : IDL.Func([OriginMapDistrict], [], []),
  'createMembership' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'id' : IDL.Opt(IDL.Nat),
          'name' : IDL.Opt(IDL.Text),
          'photoUrl' : IDL.Opt(IDL.Text),
          'identityNumber' : IDL.Opt(IDL.Text),
          'existing' : IDL.Opt(Membership),
          'isVip' : IDL.Opt(IDL.Bool),
        }),
      ],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'getAdminAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalOrders' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalMembers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAdminOrdersQueue' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllArtifacts' : IDL.Func([], [IDL.Vec(ArtifactContent)], ['query']),
  'getAllBookings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(BookingRequest)))],
      ['query'],
    ),
  'getAllDistricts' : IDL.Func([], [IDL.Vec(OriginMapDistrict)], ['query']),
  'getAllMemberships' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Membership))],
      ['query'],
    ),
  'getArtifactById' : IDL.Func([IDL.Text], [Artifact], ['query']),
  'getAvailablePackages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getCallerMembership' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCurrentLoyaltyPoints' : IDL.Func(
      [],
      [
        IDL.Nat,
        IDL.Record({
          'pointsBalance' : IDL.Nat,
          'transactions' : IDL.Vec(LoyaltyTransaction),
        }),
      ],
      ['query'],
    ),
  'getCurrentMetrics' : IDL.Func([], [IDL.Vec(SocialImpactMetric)], ['query']),
  'getDeliveryZones' : IDL.Func([], [IDL.Vec(DeliveryZone)], ['query']),
  'getKitchenQueueSummary' : IDL.Func([], [QueueSummary], ['query']),
  'getLoyaltyRewards' : IDL.Func([], [IDL.Vec(LoyaltyReward)], ['query']),
  'getOrderQueuePosition' : IDL.Func([IDL.Nat], [QueuePosition], ['query']),
  'getOriginMapForDistrict' : IDL.Func(
      [IDL.Text],
      [OriginMapDistrict],
      ['query'],
    ),
  'getPackageAddOns' : IDL.Func([], [IDL.Vec(PackageAddOn)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'requestBooking' : IDL.Func([BookingRequestDto], [BookingStatus], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArtifact' : IDL.Func([ArtifactContent], [], []),
  'updateBookingStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, BookingStatus],
      [],
      [],
    ),
  'updateDeliveryZone' : IDL.Func([DeliveryZone], [], []),
  'updateDistrict' : IDL.Func([OriginMapDistrict], [], []),
  'updateMetric' : IDL.Func([SocialImpactMetric], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'verifyMembership' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoyaltyReward = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'pointsCost' : IDL.Nat,
  });
  const PackageAddOn = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LoyaltyTransaction = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : Time,
    'isRedemption' : IDL.Bool,
    'points' : IDL.Nat,
  });
  const ArtifactContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'story' : IDL.Text,
  });
  const DeliveryZone = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'zoneId' : IDL.Text,
  });
  const OriginMapDistrict = IDL.Record({
    'id' : IDL.Text,
    'farmerPhotoUrl' : IDL.Text,
    'featuredProduct' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Membership = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'identityNumber' : IDL.Opt(IDL.Text),
    'isVerified' : IDL.Bool,
    'isVip' : IDL.Bool,
  });
  const OrderStatus = IDL.Variant({
    'Delivering' : IDL.Null,
    'Reserved' : IDL.Null,
    'Paid' : IDL.Null,
    'Default' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Ready' : IDL.Null,
    'Preparing' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'timestamp' : Time,
    'deliverTo' : IDL.Opt(IDL.Text),
  });
  const BookingStatus = IDL.Variant({
    'Rescheduled' : IDL.Null,
    'RequestedAccess' : IDL.Null,
    'Waitlist' : IDL.Null,
    'CheckedIn' : IDL.Null,
    'NoShow' : IDL.Null,
    'Reservation' : IDL.Null,
    'Default' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Denied' : IDL.Null,
    'Completed' : IDL.Null,
    'Expired' : IDL.Null,
    'Canceled' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'zone' : IDL.Text,
    'notes' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const Artifact = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'story' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const SocialImpactMetric = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Float64,
    'name' : IDL.Text,
  });
  const QueueSummary = IDL.Record({
    'totalOrders' : IDL.Nat,
    'estimatedWaitTime' : Time,
  });
  const QueuePosition = IDL.Record({
    'totalOrders' : IDL.Nat,
    'position' : IDL.Nat,
    'estimatedWaitTime' : Time,
  });
  const BookingRequestDto = IDL.Record({
    'zone' : IDL.Text,
    'notes' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoyaltyReward' : IDL.Func([LoyaltyReward], [], []),
    'addPackage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPackageAddOn' : IDL.Func([PackageAddOn], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardLoyaltyPoints' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'newBalance' : IDL.Text,
            'transactions' : IDL.Opt(IDL.Vec(LoyaltyTransaction)),
            'current' : IDL.Record({
              'pointsBalance' : IDL.Nat,
              'transactions' : IDL.Vec(LoyaltyTransaction),
            }),
            'points' : IDL.Opt(IDL.Nat),
          }),
        ],
        [],
      ),
    'createArtifact' : IDL.Func([ArtifactContent], [], []),
    'createDeliveryZone' : IDL.Func([DeliveryZone], [], []),
    'createDistrict' : IDL.Func([OriginMapDistrict], [], []),
    'createMembership' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'id' : IDL.Opt(IDL.Nat),
            'name' : IDL.Opt(IDL.Text),
            'photoUrl' : IDL.Opt(IDL.Text),
            'identityNumber' : IDL.Opt(IDL.Text),
            'existing' : IDL.Opt(Membership),
            'isVip' : IDL.Opt(IDL.Bool),
          }),
        ],
        [],
      ),
    'createOrder' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'getAdminAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalOrders' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalMembers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAdminOrdersQueue' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllArtifacts' : IDL.Func([], [IDL.Vec(ArtifactContent)], ['query']),
    'getAllBookings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(BookingRequest)))],
        ['query'],
      ),
    'getAllDistricts' : IDL.Func([], [IDL.Vec(OriginMapDistrict)], ['query']),
    'getAllMemberships' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Membership))],
        ['query'],
      ),
    'getArtifactById' : IDL.Func([IDL.Text], [Artifact], ['query']),
    'getAvailablePackages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getCallerMembership' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCurrentLoyaltyPoints' : IDL.Func(
        [],
        [
          IDL.Nat,
          IDL.Record({
            'pointsBalance' : IDL.Nat,
            'transactions' : IDL.Vec(LoyaltyTransaction),
          }),
        ],
        ['query'],
      ),
    'getCurrentMetrics' : IDL.Func(
        [],
        [IDL.Vec(SocialImpactMetric)],
        ['query'],
      ),
    'getDeliveryZones' : IDL.Func([], [IDL.Vec(DeliveryZone)], ['query']),
    'getKitchenQueueSummary' : IDL.Func([], [QueueSummary], ['query']),
    'getLoyaltyRewards' : IDL.Func([], [IDL.Vec(LoyaltyReward)], ['query']),
    'getOrderQueuePosition' : IDL.Func([IDL.Nat], [QueuePosition], ['query']),
    'getOriginMapForDistrict' : IDL.Func(
        [IDL.Text],
        [OriginMapDistrict],
        ['query'],
      ),
    'getPackageAddOns' : IDL.Func([], [IDL.Vec(PackageAddOn)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'requestBooking' : IDL.Func([BookingRequestDto], [BookingStatus], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArtifact' : IDL.Func([ArtifactContent], [], []),
    'updateBookingStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, BookingStatus],
        [],
        [],
      ),
    'updateDeliveryZone' : IDL.Func([DeliveryZone], [], []),
    'updateDistrict' : IDL.Func([OriginMapDistrict], [], []),
    'updateMetric' : IDL.Func([SocialImpactMetric], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'verifyMembership' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };