/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OriginMapDistrict {
    id: string;
    farmerPhotoUrl: string;
    featuredProduct: string;
    name: string;
    description: string;
}
export interface SocialImpactMetric {
    id: string;
    value: number;
    name: string;
}
export type Time = bigint;
export interface LoyaltyTransaction {
    id: bigint;
    description: string;
    timestamp: Time;
    isRedemption: boolean;
    points: bigint;
}
export interface BookingRequest {
    id: bigint;
    status: BookingStatus;
    zone: string;
    notes: string;
    dateTime: string;
}
export interface Artifact {
    id: string;
    title: string;
    audioUrl?: string;
    story: string;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    customer: Principal;
    timestamp: Time;
    deliverTo?: string;
}
export interface QueuePosition {
    totalOrders: bigint;
    position: bigint;
    estimatedWaitTime: Time;
}
export interface ArtifactContent {
    id: string;
    title: string;
    audioUrl?: string;
    story: string;
}
export interface DeliveryZone {
    name: string;
    description: string;
    zoneId: string;
}
export interface QueueSummary {
    totalOrders: bigint;
    estimatedWaitTime: Time;
}
export interface BookingRequestDto {
    zone: string;
    notes: string;
    dateTime: string;
}
export interface Membership {
    id: bigint;
    name: string;
    photoUrl?: string;
    identityNumber?: string;
    isVerified: boolean;
    isVip: boolean;
}
export interface LoyaltyReward {
    id: string;
    name: string;
    pointsCost: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export interface PackageAddOn {
    id: string;
    name: string;
}
export enum BookingStatus {
    Rescheduled = "Rescheduled",
    RequestedAccess = "RequestedAccess",
    Waitlist = "Waitlist",
    CheckedIn = "CheckedIn",
    NoShow = "NoShow",
    Reservation = "Reservation",
    Default = "Default",
    Confirmed = "Confirmed",
    Denied = "Denied",
    Completed = "Completed",
    Expired = "Expired",
    Canceled = "Canceled"
}
export enum OrderStatus {
    Delivering = "Delivering",
    Reserved = "Reserved",
    Paid = "Paid",
    Default = "Default",
    Confirmed = "Confirmed",
    Ready = "Ready",
    Preparing = "Preparing",
    Cancelled = "Cancelled",
    Completed = "Completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLoyaltyReward(reward: LoyaltyReward): Promise<void>;
    addPackage(packageId: string, packageName: string): Promise<void>;
    addPackageAddOn(addOn: PackageAddOn): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardLoyaltyPoints(points: bigint, description: string): Promise<{
        newBalance: string;
        transactions?: Array<LoyaltyTransaction>;
        current: {
            pointsBalance: bigint;
            transactions: Array<LoyaltyTransaction>;
        };
        points?: bigint;
    }>;
    createArtifact(artifact: ArtifactContent): Promise<void>;
    createDeliveryZone(zone: DeliveryZone): Promise<void>;
    createDistrict(district: OriginMapDistrict): Promise<void>;
    createMembership(name: string, identityNumber: string | null, photoUrl: string | null): Promise<{
        id?: bigint;
        name?: string;
        photoUrl?: string;
        identityNumber?: string;
        existing?: Membership;
        isVip?: boolean;
    }>;
    createOrder(deliverTo: string | null): Promise<bigint>;
    getAdminAnalytics(): Promise<{
        totalOrders: bigint;
        totalBookings: bigint;
        totalUsers: bigint;
        totalMembers: bigint;
    }>;
    getAdminOrdersQueue(): Promise<Array<Order>>;
    getAllArtifacts(): Promise<Array<ArtifactContent>>;
    getAllBookings(): Promise<Array<[Principal, Array<BookingRequest>]>>;
    getAllDistricts(): Promise<Array<OriginMapDistrict>>;
    getAllMemberships(): Promise<Array<[Principal, Membership]>>;
    getArtifactById(id: string): Promise<Artifact>;
    getAvailablePackages(): Promise<Array<string>>;
    getCallerBookings(): Promise<Array<BookingRequest>>;
    getCallerMembership(): Promise<Membership | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientOrders(): Promise<Array<Order>>;
    getCurrentLoyaltyPoints(): Promise<[bigint, {
            pointsBalance: bigint;
            transactions: Array<LoyaltyTransaction>;
        }]>;
    getCurrentMetrics(): Promise<Array<SocialImpactMetric>>;
    getDeliveryZones(): Promise<Array<DeliveryZone>>;
    getKitchenQueueSummary(): Promise<QueueSummary>;
    getLoyaltyRewards(): Promise<Array<LoyaltyReward>>;
    getOrderQueuePosition(orderId: bigint): Promise<QueuePosition>;
    getOriginMapForDistrict(districtId: string): Promise<OriginMapDistrict>;
    getPackageAddOns(): Promise<Array<PackageAddOn>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    redeemLoyaltyPoints(rewardId: string, pointsCost: bigint): Promise<void>;
    requestBooking(request: BookingRequestDto): Promise<BookingStatus>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    secureBootAdmin(firstAdmin: Principal, adminToken: string): Promise<boolean>;
    updateArtifact(artifact: ArtifactContent): Promise<void>;
    updateBookingStatus(user: Principal, bookingId: bigint, status: BookingStatus): Promise<void>;
    updateDeliveryZone(zone: DeliveryZone): Promise<void>;
    updateDistrict(district: OriginMapDistrict): Promise<void>;
    updateMetric(metric: SocialImpactMetric): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    verifyMembership(user: Principal, isVerified: boolean): Promise<void>;
}
import type { Artifact as _Artifact, ArtifactContent as _ArtifactContent, BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, LoyaltyTransaction as _LoyaltyTransaction, Membership as _Membership, Order as _Order, OrderStatus as _OrderStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLoyaltyReward(arg0: LoyaltyReward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLoyaltyReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLoyaltyReward(arg0);
            return result;
        }
    }
    async addPackage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackage(arg0, arg1);
            return result;
        }
    }
    async addPackageAddOn(arg0: PackageAddOn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackageAddOn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackageAddOn(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardLoyaltyPoints(arg0: bigint, arg1: string): Promise<{
        newBalance: string;
        transactions?: Array<LoyaltyTransaction>;
        current: {
            pointsBalance: bigint;
            transactions: Array<LoyaltyTransaction>;
        };
        points?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.awardLoyaltyPoints(arg0, arg1);
                return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardLoyaltyPoints(arg0, arg1);
            return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createArtifact(arg0: ArtifactContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createArtifact(to_candid_ArtifactContent_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArtifact(to_candid_ArtifactContent_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDeliveryZone(arg0: DeliveryZone): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeliveryZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeliveryZone(arg0);
            return result;
        }
    }
    async createDistrict(arg0: OriginMapDistrict): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDistrict(arg0);
            return result;
        }
    }
    async createMembership(arg0: string, arg1: string | null, arg2: string | null): Promise<{
        id?: bigint;
        name?: string;
        photoUrl?: string;
        identityNumber?: string;
        existing?: Membership;
        isVip?: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembership(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_record_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembership(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_record_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAdminAnalytics(): Promise<{
        totalOrders: bigint;
        totalBookings: bigint;
        totalUsers: bigint;
        totalMembers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics();
            return result;
        }
    }
    async getAdminOrdersQueue(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminOrdersQueue();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminOrdersQueue();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArtifacts(): Promise<Array<ArtifactContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtifacts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtifacts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<[Principal, Array<BookingRequest>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDistricts(): Promise<Array<OriginMapDistrict>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDistricts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDistricts();
            return result;
        }
    }
    async getAllMemberships(): Promise<Array<[Principal, Membership]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemberships();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemberships();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtifactById(arg0: string): Promise<Artifact> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtifactById(arg0);
                return from_candid_Artifact_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtifactById(arg0);
            return from_candid_Artifact_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailablePackages(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailablePackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailablePackages();
            return result;
        }
    }
    async getCallerBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerMembership(): Promise<Membership | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMembership();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMembership();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientOrders();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientOrders();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentLoyaltyPoints(): Promise<[bigint, {
            pointsBalance: bigint;
            transactions: Array<LoyaltyTransaction>;
        }]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentLoyaltyPoints();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentLoyaltyPoints();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getCurrentMetrics(): Promise<Array<SocialImpactMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentMetrics();
            return result;
        }
    }
    async getDeliveryZones(): Promise<Array<DeliveryZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryZones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryZones();
            return result;
        }
    }
    async getKitchenQueueSummary(): Promise<QueueSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getKitchenQueueSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKitchenQueueSummary();
            return result;
        }
    }
    async getLoyaltyRewards(): Promise<Array<LoyaltyReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyRewards();
            return result;
        }
    }
    async getOrderQueuePosition(arg0: bigint): Promise<QueuePosition> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderQueuePosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderQueuePosition(arg0);
            return result;
        }
    }
    async getOriginMapForDistrict(arg0: string): Promise<OriginMapDistrict> {
        if (this.processError) {
            try {
                const result = await this.actor.getOriginMapForDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOriginMapForDistrict(arg0);
            return result;
        }
    }
    async getPackageAddOns(): Promise<Array<PackageAddOn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackageAddOns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackageAddOns();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async redeemLoyaltyPoints(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemLoyaltyPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemLoyaltyPoints(arg0, arg1);
            return result;
        }
    }
    async requestBooking(arg0: BookingRequestDto): Promise<BookingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.requestBooking(arg0);
                return from_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestBooking(arg0);
            return from_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async secureBootAdmin(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.secureBootAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.secureBootAdmin(arg0, arg1);
            return result;
        }
    }
    async updateArtifact(arg0: ArtifactContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArtifact(to_candid_ArtifactContent_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArtifact(to_candid_ArtifactContent_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingStatus(arg0: Principal, arg1: bigint, arg2: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, arg1, to_candid_BookingStatus_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, arg1, to_candid_BookingStatus_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateDeliveryZone(arg0: DeliveryZone): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryZone(arg0);
            return result;
        }
    }
    async updateDistrict(arg0: OriginMapDistrict): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDistrict(arg0);
            return result;
        }
    }
    async updateMetric(arg0: SocialImpactMetric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMetric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMetric(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyMembership(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMembership(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMembership(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ArtifactContent_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArtifactContent): ArtifactContent {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Artifact_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Artifact): Artifact {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BookingRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Membership_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Membership): Membership {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Membership]): Membership | null {
    return value.length === 0 ? null : from_candid_Membership_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_LoyaltyTransaction>]): Array<LoyaltyTransaction> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    photoUrl: [] | [string];
    identityNumber: [] | [string];
    isVerified: boolean;
    isVip: boolean;
}): {
    id: bigint;
    name: string;
    photoUrl?: string;
    identityNumber?: string;
    isVerified: boolean;
    isVip: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        photoUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.photoUrl)),
        identityNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.identityNumber)),
        isVerified: value.isVerified,
        isVip: value.isVip
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    customer: Principal;
    timestamp: _Time;
    deliverTo: [] | [string];
}): {
    id: bigint;
    status: OrderStatus;
    customer: Principal;
    timestamp: Time;
    deliverTo?: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n18(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        timestamp: value.timestamp,
        deliverTo: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliverTo))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    audioUrl: [] | [string];
    story: string;
}): {
    id: string;
    title: string;
    audioUrl?: string;
    story: string;
} {
    return {
        id: value.id,
        title: value.title,
        audioUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.audioUrl)),
        story: value.story
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    zone: string;
    notes: string;
    dateTime: string;
}): {
    id: bigint;
    status: BookingStatus;
    zone: string;
    notes: string;
    dateTime: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n28(_uploadFile, _downloadFile, value.status),
        zone: value.zone,
        notes: value.notes,
        dateTime: value.dateTime
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newBalance: string;
    transactions: [] | [Array<_LoyaltyTransaction>];
    current: {
        pointsBalance: bigint;
        transactions: Array<_LoyaltyTransaction>;
    };
    points: [] | [bigint];
}): {
    newBalance: string;
    transactions?: Array<LoyaltyTransaction>;
    current: {
        pointsBalance: bigint;
        transactions: Array<LoyaltyTransaction>;
    };
    points?: bigint;
} {
    return {
        newBalance: value.newBalance,
        transactions: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.transactions)),
        current: value.current,
        points: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.points))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: [] | [bigint];
    name: [] | [string];
    photoUrl: [] | [string];
    identityNumber: [] | [string];
    existing: [] | [_Membership];
    isVip: [] | [boolean];
}): {
    id?: bigint;
    name?: string;
    photoUrl?: string;
    identityNumber?: string;
    existing?: Membership;
    isVip?: boolean;
} {
    return {
        id: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.id)),
        name: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.name)),
        photoUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.photoUrl)),
        identityNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.identityNumber)),
        existing: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.existing)),
        isVip: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.isVip))
    };
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_BookingRequest>]): [Principal, Array<BookingRequest>] {
    return [
        value[0],
        from_candid_vec_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _Membership]): [Principal, Membership] {
    return [
        value[0],
        from_candid_Membership_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivering: null;
} | {
    Reserved: null;
} | {
    Paid: null;
} | {
    Default: null;
} | {
    Confirmed: null;
} | {
    Ready: null;
} | {
    Preparing: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
}): OrderStatus {
    return "Delivering" in value ? OrderStatus.Delivering : "Reserved" in value ? OrderStatus.Reserved : "Paid" in value ? OrderStatus.Paid : "Default" in value ? OrderStatus.Default : "Confirmed" in value ? OrderStatus.Confirmed : "Ready" in value ? OrderStatus.Ready : "Preparing" in value ? OrderStatus.Preparing : "Cancelled" in value ? OrderStatus.Cancelled : "Completed" in value ? OrderStatus.Completed : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rescheduled: null;
} | {
    RequestedAccess: null;
} | {
    Waitlist: null;
} | {
    CheckedIn: null;
} | {
    NoShow: null;
} | {
    Reservation: null;
} | {
    Default: null;
} | {
    Confirmed: null;
} | {
    Denied: null;
} | {
    Completed: null;
} | {
    Expired: null;
} | {
    Canceled: null;
}): BookingStatus {
    return "Rescheduled" in value ? BookingStatus.Rescheduled : "RequestedAccess" in value ? BookingStatus.RequestedAccess : "Waitlist" in value ? BookingStatus.Waitlist : "CheckedIn" in value ? BookingStatus.CheckedIn : "NoShow" in value ? BookingStatus.NoShow : "Reservation" in value ? BookingStatus.Reservation : "Default" in value ? BookingStatus.Default : "Confirmed" in value ? BookingStatus.Confirmed : "Denied" in value ? BookingStatus.Denied : "Completed" in value ? BookingStatus.Completed : "Expired" in value ? BookingStatus.Expired : "Canceled" in value ? BookingStatus.Canceled : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArtifactContent>): Array<ArtifactContent> {
    return value.map((x)=>from_candid_ArtifactContent_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_BookingRequest>]>): Array<[Principal, Array<BookingRequest>]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _Membership]>): Array<[Principal, Membership]> {
    return value.map((x)=>from_candid_tuple_n31(_uploadFile, _downloadFile, x));
}
function to_candid_ArtifactContent_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArtifactContent): _ArtifactContent {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    audioUrl?: string;
    story: string;
}): {
    id: string;
    title: string;
    audioUrl: [] | [string];
    story: string;
} {
    return {
        id: value.id,
        title: value.title,
        audioUrl: value.audioUrl ? candid_some(value.audioUrl) : candid_none(),
        story: value.story
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    Rescheduled: null;
} | {
    RequestedAccess: null;
} | {
    Waitlist: null;
} | {
    CheckedIn: null;
} | {
    NoShow: null;
} | {
    Reservation: null;
} | {
    Default: null;
} | {
    Confirmed: null;
} | {
    Denied: null;
} | {
    Completed: null;
} | {
    Expired: null;
} | {
    Canceled: null;
} {
    return value == BookingStatus.Rescheduled ? {
        Rescheduled: null
    } : value == BookingStatus.RequestedAccess ? {
        RequestedAccess: null
    } : value == BookingStatus.Waitlist ? {
        Waitlist: null
    } : value == BookingStatus.CheckedIn ? {
        CheckedIn: null
    } : value == BookingStatus.NoShow ? {
        NoShow: null
    } : value == BookingStatus.Reservation ? {
        Reservation: null
    } : value == BookingStatus.Default ? {
        Default: null
    } : value == BookingStatus.Confirmed ? {
        Confirmed: null
    } : value == BookingStatus.Denied ? {
        Denied: null
    } : value == BookingStatus.Completed ? {
        Completed: null
    } : value == BookingStatus.Expired ? {
        Expired: null
    } : value == BookingStatus.Canceled ? {
        Canceled: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivering: null;
} | {
    Reserved: null;
} | {
    Paid: null;
} | {
    Default: null;
} | {
    Confirmed: null;
} | {
    Ready: null;
} | {
    Preparing: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} {
    return value == OrderStatus.Delivering ? {
        Delivering: null
    } : value == OrderStatus.Reserved ? {
        Reserved: null
    } : value == OrderStatus.Paid ? {
        Paid: null
    } : value == OrderStatus.Default ? {
        Default: null
    } : value == OrderStatus.Confirmed ? {
        Confirmed: null
    } : value == OrderStatus.Ready ? {
        Ready: null
    } : value == OrderStatus.Preparing ? {
        Preparing: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Completed ? {
        Completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
